export const BLOG_IMG_URL = 'https://premiertour-production.up.railway.app/files/blog_images/'
export const COUNTRY_IMG_URL = 'https://premiertour-production.up.railway.app/files/country_images/'
export const CUSTOMER_IMG_URL = 'https://premiertour-production.up.railway.app/files/view_card_images/'
export const TOUR_CARD_IMG_URL = 'https://premiertour-production.up.railway.app/files/tour_card_images/'
export const TOUR_IMG_URL = 'https://premiertour-production.up.railway.app/files/tour_images/'